### teste de buscar consulta por ID
POST http://localhost:40000/Login HTTP/1.1
content-type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2NzQ3ODI5NzksInVzZXJuYW1lIjoicXdlIn0.SlYYCm8J6wlpb3i1jJcSvhSz6VjwKvzPOxza8P6-hzo

{    
    "username": "qwe",
    "password": "qwe"
}


### teste de buscar todos os consultas
GET http://localhost:40000/getAllConsultas HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTcwMDY2MjI3MywiZXhwIjoxNzAwNjYyODczfQ.rWDZnMH2r2W8C5IWy0jY7bpcn069s4Qi9aYYLl4JWA4

{    
    
}

### teste de buscar consulta por ID
POST http://localhost:40000/getConsultasByID HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTcwMDY2MzY0MiwiZXhwIjoxNzAwNjY0MjQyfQ.4PWmkiCUTYVYIj8KLQq0Nz4jWguRDQKSiI7YD6C01Uw

{    
    "consultaid": 1
}

### teste de inserção de consulta
POST http://localhost:40000/insertConsultas HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTcwMDU2OTI4NSwiZXhwIjoxNzAwNTY5ODg1fQ.DYXQPZxdENYxvZC6jPaFd-U6mAit_in5sNwm7b6tdUk

{    
    "consultaid": 3,
    "codigo": "C003",
    "dataconsulta": "2024-01-24",
    "medicoid": 1,
    "pacienteid": 1,
    "deleted": false
}

### teste de atualização de consulta
POST http://localhost:40000/updateConsultas HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTcwMDU2OTI4NSwiZXhwIjoxNzAwNTY5ODg1fQ.DYXQPZxdENYxvZC6jPaFd-U6mAit_in5sNwm7b6tdUk

{    
    "consultaid": 2,
    "codigo": "C002",
    "dataconsulta": "2023-03-12",
    "medicoid": 2,
    "pacienteid": 2,
    "deleted": false
}

### teste de atualização de consulta
POST http://localhost:40000/DeleteConsultas HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTcwMDU2OTI4NSwiZXhwIjoxNzAwNTY5ODg1fQ.DYXQPZxdENYxvZC6jPaFd-U6mAit_in5sNwm7b6tdUk

{    
    "consultaid": 3  
}