### teste de buscar paciente por ID
POST http://localhost:40000/Login HTTP/1.1
content-type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2NzQ3ODI5NzksInVzZXJuYW1lIjoicXdlIn0.SlYYCm8J6wlpb3i1jJcSvhSz6VjwKvzPOxza8P6-hzo

{    
    "username": "qwe",
    "password": "qwe"
}


### teste de buscar todos os pacientes
GET http://localhost:40000/getAllPacientes HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTcwMDU2NzAwMywiZXhwIjoxNzAwNTY3NjAzfQ.xAe847RB-GYHPf1KIzuyqN03OzbMsPPXNozKi30L5A8

{    
    
}

### teste de buscar paciente por ID
POST http://localhost:40000/getPacientesByID HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTcwMDU2NzAwMywiZXhwIjoxNzAwNTY3NjAzfQ.xAe847RB-GYHPf1KIzuyqN03OzbMsPPXNozKi30L5A8

{    
    "pacienteid": 1
}

### teste de inserção de paciente
POST http://localhost:40000/insertPacientes HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTcwMDU2NzAwMywiZXhwIjoxNzAwNTY3NjAzfQ.xAe847RB-GYHPf1KIzuyqN03OzbMsPPXNozKi30L5A8

{    
    "pacienteid": 0,
    "cpf": "222.222.222-22",
    "nome": "Carlos das Matias",
    "endereco": " Rua das couves",
    "datanascimento": "1999-12-12",
    "deleted": false
}

### teste de atualização de paciente
POST http://localhost:40000/updatePacientes HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTcwMDU2NzAwMywiZXhwIjoxNzAwNTY3NjAzfQ.xAe847RB-GYHPf1KIzuyqN03OzbMsPPXNozKi30L5A8

{    
    "pacienteid": 2,
    "cpf": "555.555.555-55",
    "nome": "Josue das Neves",
    "endereco": "Rua das Flores",
    "datanascimento": "1978-08-22",
    "deleted": false
}

### teste de atualização de paciente
POST http://localhost:40000/DeletePacientes HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTcwMDU2NzAwMywiZXhwIjoxNzAwNTY3NjAzfQ.xAe847RB-GYHPf1KIzuyqN03OzbMsPPXNozKi30L5A8

{    
    "pacienteid": 5
}
